try{
    let a = 2 + b;
}catch(e){ // O bloco Catch Ã© executado se no blobo Try tivrt algum erro
    console.log(e);
}

console.log("teste");